# Generated by Django 5.0.7 on 2024-07-17 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_delete_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='applied_at',
        ),
    ]
