# Generated by Django 5.0.7 on 2024-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobapplication_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
