# Generated by Django 5.0.7 on 2024-07-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobposting_remove_jobapplication_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelance', 'Freelance'), ('Internship', 'Internship')], max_length=100),
        ),
    ]
